- name: Create SonarQube user
  user:
    name: sonarqube
  become: yes
  become_method: enable
  allow_world_readable_tmpfiles: true

- name: Install Java version 17
  apt:
    name: openjdk-17-jdk
    state: present

- name: Add lines to /etc/sysctl.conf
  lineinfile:
      dest: /etc/sysctl.conf
      line: "{{ item }}"
  with_items:
    - 'vm.max_map_count=524288'
    - 'fs.file-max=131072'

- name: Reload the system changes
  command: sysctl --system

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - unzip
      - software-properties-common
      - wget

- name: Download SonarQube
  get_url:
    url: "{{ sonarqube_zip_url }}"
    dest: "{{ sonarqube_zip_dest }}"

- name: Unarchive SonarQube
  unarchive:
    src: "{{ sonarqube_zip_dest }}"
    dest: "{{ sonarqube_unarchive_dest }}"
    remote_src: yes

- name: Rename SonarQube directory
  shell: mv {{ sonarqube_unarchive_dest }}/sonarqube-{{ sonarqube_version }} {{ sonarqube_final_dir }}

- name: Replace sonar.web.port in /opt/sonarqube/conf/sonar.properties
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: '^(\.*)sonar.web.port=9000(\.*)$'
    line: 'sonar.web.port=9000'
    backrefs: yes

- name: Replace sonar.search.javaOpts in /opt/sonarqube/conf/sonar.properties
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: '^(\.*)sonar.search.javaOpts=.*(\.*)$'
    line: 'sonar.search.javaOpts=-Xmx512m -Xms512m -XX:MaxDirectMemorySize=256m -XX:+HeapDumpOnOutOfMemoryError'
    backrefs: yes

- name: Replace sonar.log.level in /opt/sonarqube/conf/sonar.properties
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: '^(\.*)#sonar.log.level=INFO(\.*)$'
    line: 'sonar.log.level=INFO'
    backrefs: yes
      
- name: Replace sonar.web.javaAdditionalOpts in /opt/sonarqube/conf/sonar.properties
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: '^(\.*)sonar.web.javaAdditionalOpts=.*(\.*)$'
    line: 'sonar.web.javaAdditionalOpts=-server'
    backrefs: yes
        
- name: Replace sonar.path.logs in /opt/sonarqube/conf/sonar.properties
  lineinfile:
    path: /opt/sonarqube/conf/sonar.properties
    regexp: '^(\.*)#sonar.path.logs=logs(\.*)$'
    line: 'sonar.path.logs=logs'
    backrefs: yes

- name: Add sonarqube.service
  template:
    src: sonarqube.service
    dest: /etc/systemd/system/sonarqube.service

- name: Force systemd to reread configs
  systemd:
    daemon_reload: true

- name: Start SonarQube service
  service:
    name: sonarqube
    state: started
    enabled: yes