---
- name: Create SonarQube directories on the control node
  module: file
  path: ~/ansible/sonarqube
  state: directory
  run_once: true

- name: Change directory to ~/ansible/sonarqube
  module: command
  argv: chdir=~/ansible/sonarqube
  run_once: true

- name: Pull SonarQube Docker image
  docker_image:
    name: sonarqube
    source: pull

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube
    state: started
    ports:
      - "9000:9000"
    volumes:
      - "{{ sonarqube_conf_dir }}:/opt/sonarqube/conf"
      - "{{ sonarqube_data_dir }}:/opt/sonarqube/data"
      - "{{ sonarqube_logs_dir }}:/opt/sonarqube/logs"
      - "{{ sonarqube_extensions_dir }}:/opt/sonarqube/extensions"
    env:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"