---
- name: Uninstall Java 8 and Java 11
  hosts: build_server
  become: yes
  tasks:
    - name: Remove Java 8
      apt:
        name: openjdk-8-jdk
        state: absent
      when: ansible_facts.packages['openjdk-8-jdk']

    - name: Remove Java 11
      apt:
        name: openjdk-11-jdk
        state: absent
      when: ansible_facts.packages['openjdk-11-jdk']
