
- name: Pull the latest Nexus Docker image
  docker_image:
    name: "{{ nexus_image }}"
    source: pull

- name: Create Nexus volume
  docker_volume:
    name: "nexus-data"

- name: Run Nexus container
  docker_container:
    name: "{{ nexus_container_name }}"
    image: "{{ nexus_image }}"
    state: started
    restart_policy: unless-stopped
    ports: "{{ nexus_ports }}"
    volumes:
          - "{{ nexus_volume }}"

# - name: Ensure Nexus container is running
#   docker_container_info:
#     name: "{{ nexus_container_name }}"
#   register: container_info

# - name: Fail if Nexus container is not running
#   fail:
#     msg: "Nexus container is not running!"
#   when: container_info.containers[0].State.Status != 'running'

- name: Retrieve Nexus admin password
  shell: "cat /var/lib/docker/volumes/nexus-data/_data/admin.password"
  register: nexus_admin_password

- name: Display Nexus admin password
  debug:
    msg: "Nexus admin password is {{ nexus_admin_password.stdout }}"
