- name: Install Nexus Repository Manager
  hosts: nexus_vm
  become: true
  tasks:
    - name: Install OpenJDK 
      apt:
        name: openjdk-{{java_version}}-jdk
        state: present

    - name: Check & create downloads dir
      file:
        path: '{{ nexus_home_parent_directory}}'
        state: directory
        mode: 0755

    - name: Checking if Nexux is already installed
      stat: 
        path: '{{ nexus_home_parent_directory }}/nexus-{{ nexus_version }}'
        register: nexus_installed

    - name: Download Nexus
      get_url:
        url: '{{nexus_download_url}}'
        dest: '{{nexus_home_parent_directory}}/{{ nexus_file_name }}'
      when: nexus_installed.stat.exists != True  

    - name: Unzip Nexus
      unarchive:
        src: '{{ nexus_home_parent_directory}}/{{ nexus_file_name }}'
        dest: '{{ nexus_home_parent_directory}}'
        remote_src: yes
      when: nexus_installed.stat.exists != True

    - name: Set Permissions
      file:
        path: '{{nexus_home_parent_directory}}'
        state: directory
        mode: '0755'

    - name: Start Nexus Service
      service:
        name: nexus
        state: started

    - name: Cleaning Up
      file:
        state: absent
        path: '{{ nexus_home_parent_directory}}/{{ nexus_file_name }}'
  