- name: Pull the Sonar Docker Image
  docker_image:
    name: sonarqube
    source: pull

- name: Create a Docker Network
  docker_network:
    name: sonar-network
    state: present

- name: Start a Database Container
  docker_container:
    name: sonar-db
    image: postgres:9.6
    state: started
    networks:
      - name: sonar-network
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: "{{ postgres_db }}"


- name: Start the Sonar Container
  docker_container:
    name: sonar
    image: sonarqube
    state: started
    ports:
      - "9000:9000"
    networks:
      - name: sonar-network
    env:
      SONARQUBE_JDBC_URL: "{{sonarqube_jdbc_url}}"
      SONAR_JDBC_USERNAME: "{{sonar_jdbc_username}}"
      SONAR_JDBC_PASSWORD: "{{sonar_jdbc_password}}" 