---
docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo_url: "https://download.docker.com/linux/ubuntu"
docker_key_path: "/etc/apt/keyrings/docker.asc"
docker_user: "ubuntu"
os_arch: "amd64"