---
- name: Add Jenkins Repository
  apt_repository:
    repo: "{{ jenkins_repo }}"
    state: present
    update_cache: yes

- name: Import Jenkins Repository GPG Key
  apt_key:
    url: "{{ jenkins_gpg_key }}"
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start Jenkins Service
  service:
    name: jenkins
    state: started
    enabled: yes
