- name: Create Artifactory home directory
  file:
    path: "/ubuntu/home/jforg/artifactory/var/etc/"
    state: directory
    mode: "0755"
    owner: 1030
    group: 1030
    
- name: Generate master key for Artifactory
  vars:
    master_key: "{{ lookup('password', '/dev/null length=32 chars=hex') }}"
  debug:
    msg: "Master key generated: {{ master_key }}"

- name: Copy the generated master key to the file
  copy:
    content: "{{ master_key }}"
    dest: /ubuntu/home/jfrog/artifactory/var/etc/master.key
    owner: 1030
    group: 1030
    mode: '0600'
  creates: /ubuntu/home/jfrog/artifactory/var/etc/master.key

    
- name: Create system.yaml file
  copy:
    content: |
      shared:
        database:
          driver: org.postgresql.Driver
          type: postgresql
          url: jdbc:postgresql://artifactory-postgres:5432/artifactorydb
          username: artifactory
          password: password
    dest: "/ubuntu/home/jforg/artifactory/var/etc/system.yaml"
    owner: 1030
    group: 1030
    mode: "0644"
    
- name: Run PostgreSQL Docker container
  docker_container:
    name: artifactory-postgres
    image: postgres:latest
    state: started
    restart_policy: unless-stopped
    env:
      POSTGRES_USER: artifactory
      POSTGRES_PASSWORD: password
      POSTGRES_DB: artifactorydb
    ports:
      - 5432:5432
      
- name: Run Artifactory Docker container
  docker_container:
    name: artifactory
    image: releases-docker.jfrog.io/jfrog/artifactory-pro:7.90.7
    state: started
    restart_policy: unless-stopped
    volumes:
      - "/ubuntu/home/jforg/artifactory/var/:/var/opt/jfrog/artifactory"
    env:
      DB_TYPE: postgresql
      DB_HOST: artifactory-postgres
      DB_USER: artifactory
      DB_PASSWORD: password
      DB_URL: jdbc:postgresql://artifactory-postgres:5432/artifactorydb
    ports:
      - 8081:8081
      - 8082:8082   
