---
- name: Install prerequisite packages
  apt:
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: "{{docker_gpg_url}}"
    state: present
  notify: reload apt cache

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_url }} $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable"
    state: present
    filename: docker
  notify: reload apt cache


- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker 23.0.1-1
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
 
- name: Setup docker user
  user:
    name: docker
    groups: "docker"
    append: true
    sudo_user: true 
        
- name: Install Docker-Compose & Set Permission
  get_url:
    url: "{{docker_compose_url}}"
    dest: /usr/local/bin/docker-compose
    mode: '755'
    
- name: Create Docker-Compose symlink
  ansible.builtin.command:
    cmd: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    creates: /usr/bin/docker-compose

 
- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true