---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisite packages
  apt:
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker's official GPG key directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "{{ docker_gpg_url }}"
    dest: "{{docker_key_path}}"
    mode: '0644'
  notify: reload apt cache

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by={{docker_key_path}}] {{ docker_repo_url }} {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
  notify: reload apt cache



- name: Install Docker packages
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to Docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
 