
- name: Update the package lists
  apt:
    update_cache: yes

- name: Ensure required packages are installed
  apt:
    name:
      - curl
      - ca-certificates
    state: present

- name: Create directory for PostgreSQL key
  file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    mode: '0755'

- name: Download PostgreSQL signing key
  get_url:
    url: "{{ pgdg_key_url }}"
    dest: "{{ pgdg_key_path }}"
    mode: '0644'

- name: Create the PostgreSQL repository configuration file
  copy:
    content: "{{ pgdg_repo }}"
    dest: "{{ pgdg_repo_file }}"
    mode: '0644'

- name: Update the package lists
  apt:
    update_cache: yes

- name: Install the latest version of PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Adding postgres to sudoer file
  lineinfile:
    dest: /etc/sudoers
    line: '{{item}}'
  with_items:
    - 'postgres ALL=(ALL:ALL) ALL' 


- name: Ensure POSTGRESQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create sonarqube user
  become_user: postgres
  shell: sudo -u postgres psql -c "CREATE USER sonarqube WITH PASSWORD 'sonarqube';"

- name: Create sonarqube database
  become_user: postgres
  shell:
    sudo -u postgres createdb --owner=sonarqube sonarqube