
- name: Update the package lists
  apt:
    update_cache: yes

- name: Ensure required packages are installed
  apt:
    name:
      - curl
      - ca-certificates
      - p
    state: present

- name: Create directory for PostgreSQL key
  file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    mode: '0755'

- name: Download PostgreSQL signing key
  get_url:
    url: "{{ pgdg_key_url }}"
    dest: "{{ pgdg_key_path }}"
    mode: '0644'

- name: Create the PostgreSQL repository configuration file
  copy:
    content: "{{ pgdg_repo }}"
    dest: "{{ pgdg_repo_file }}"
    mode: '0644'

- name: Update the package lists
  apt:
    update_cache: yes

- name: Checking if PostgreSQL is already installed
  stat: 
    path: /etc/postgresql
  register: postgres_installed

- name: Install the latest version of PostgreSQL
  apt:
    pkg: '{{item}}'
  with_items:
    - postgresql
    - python3-psycopg2
  when: postgres_installed.stat.exists != True

- name: Adding postgres to sudoer file
  lineinfile:
    dest: /etc/sudoers
    line: '{{item}}'
  with_items:
    - 'postgres ALL=(ALL:ALL) ALL' 


- name: Ensure POSTGRESQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Install ACL
  apt:
    name: acl
    state: present

# - name: Create sonarqube user
#   become_user: postgres
#   shell: sudo -u postgres psql -c "CREATE USER sonarqube WITH PASSWORD 'sonarqube';"

- name: Ensure sonarqube user is present
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: sonarqube
    password: sonarqube
    state: present

# - name: Create sonarqube database
#   become_user: postgres
#   shell:
#     sudo -u postgres createdb --owner=sonarqube sonarqube

- name: Ensure the sonarqube database is present
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: sonarqube
    owner: sonarqube
    state: present
